sudo: required
language: csharp
dist: xenial
mono: none
dotnet: 2.2
os:
- linux
solution: LotteryApp.sln
install:
- dotnet restore
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 5 # give Web server some time to bind to sockets, etc
script:
  - dotnet restore
  - dotnet build --configuration Release
  - dotnet test Lottery.Models.Test/Lottery.Models.Test.csproj
  - dotnet test Lottery.Service.Tests/Lottery.Service.Tests.csproj
  - dotnet test Lottery.Api.Test/LotteryApi.Test.csproj