language: csharp
dist: trusty
mono: none
dotnet: 2.0.9
install:
- dotnet restore
script:
- dotnet build
- dotnet test Lottery.Models.Test/Lottery.Models.Test.csproj
- dotnet test Lottery.Service.Tests/Lottery.Service.Tests.csproj
- dotnet test Lottery.Api.Test/LotteryApi.Test.csproj
