    
image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: LotteryApp.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:rsmivb -target:"xunit.console.x86.exe" -targetargs:".\Lottery.Models.Test\bin\Debug\Lottery.Models.Test.dll -noshadow"  -output:".\Lottery.Models.Test.xml"
- codecov -f "Lottery.Models.Test.xml"