
image: Visual Studio 2017

branches:
  only:
  - master
environment:
  SONAR_TOKEN:
    secure: 1le4hKhDyj6UuukBpuVK6a7LQT98MINrDKnDilQI8HhW5sYHWKzZnROmphFDHc2/

skip_commits:
  files:
  - README.md

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit
  - dotnet tool install -g dotnet-sonarscanner

build:
  project: LotteryApi.sln
  verbosity: minimal

after_build:
  - ps: dotnet-sonarscanner begin /k:"rsmivb_LotteryApp" /o:"rsmivb-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:SONAR_TOKEN"
  - dotnet build .\LotteryApi\LotteryApi.csproj
  - ps: dotnet-sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
test_script:
  - OpenCover.Console.exe -register:rsmivb -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"Lottery.Api.Test\bin\Debug\netcoreapp2.2\LotteryApi.Test.dll -noshadow" -oldStyle -output:".\coverage.xml" -coverbytest:"XUnit"
  - codecov -f .\coverage.xml -t 2df170bb-1daf-4eac-923a-9454b8b1ed35
